### ISSUE TITLE
Variable importance not supported for LGBM.

### ISSUE THREAD

**Issue by nipnipj** [markjrieke/workboots#53]
Hello!
```
Model-specific variable importance scores are currently not available for this type of model.
```
Please, add it to you list of new features. Thanks.

**Comment by markjrieke** [comment]
workboots uses the [vip](https://github.com/koalaverse/vip/tree/d2688667e7f8da7c38c95fff24212dd4ce5bba0f) package under the hood to estimate variable importance. Please open an issue there to request support for additional models
